[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["node ./node_modules/vite/bin/vite.js build"]

[start]
cmd = "node ./node_modules/vite/bin/vite.js preview --host 0.0.0.0 --port $PORT"